version: '3.3'
services:  
  app:
    image: richavarma/mlops_repo:latest
    command: >
      sh -c "python app.py wait_for_mysqldb &&
             python social_distance_det.py &&
             python main.py"
    environment:
      - DISPLAY=:0
    depends_on:
      - mysqldb
    ports:
      - "5000:5000"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/sdm_logfile.log:/app/sdm_logfile.log
  
  mysqldb:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "5423:5423"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    volumes:
      - /tmp/db:/docker-entrypoint-initdb.d/:ro
    tty: true

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.7.1
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    stdin_open: true
    tty: true
    network_mode: bridge
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "50"
  kibana:
    container_name: kibana
    image: kibana:7.7.1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 5601:5601
    environment: 
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    stdin_open: true
    tty: true
    network_mode: bridge
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "50"
  logstash:
    container_name: logstash
    image: logstash:7.7.1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /tmp/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - 5044:5044
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    stdin_open: true
    tty: true
    network_mode: bridge
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "50"
  filebeat:
    user: root
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:7.7.1
    links:
      - logstash:logstash
    depends_on:
      - logstash
    volumes:
      - /var/run/docker.sock:/host_docker/docker.sock
      - /var/lib/docker:/host_docker/var/lib/docker
      - /home/richa/Desktop/final_proj/SPE_Social_Distancing_Monitor/sdm_logfile.log:/usr/share/filebeat/mylog/sdm_logfile.log
      - /tmp/filebeat.yml:/usr/share/filebeat/filebeat.yml
    command: ["--strict.perms=false"]
    ulimits:
      memlock:
        soft: -1
        hard: -1
    stdin_open: true
    tty: true
    network_mode: bridge
    deploy:
      mode: global
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "50"
