version: '2.2'
services:  
  app:
    image: richavarma/mlops_repo:latest
    command: >
      sh -c "python app.py wait_for_db &&
             python social_distance_det.py &&
             python main.py runserver 0.0.0.0:5002"
    links:
      - db
    ports:
      - "5002:5002"
  
  db:
    image: mysql:latest
    ports:
      - "32001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql/:ro
            - ./myvol:/var/lib/mysql
